version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/postgres_db"
      PORT: 4000
      MIX_ENV: prod
      SECRET_KEY_BASE: "your_production_secret_key_base"
      AWS_ACCESS_KEY_ID: "your_access_key_id"
      AWS_SECRET_ACCESS_KEY: "your_secret_access_key"
      AWS_REGION: "your_region"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
