version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    volumes:
      - '..:/app:cached'
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/postgres_db"
      PORT: 4000
      MIX_ENV: dev
      SECRET_KEY_BASE: "some_secret_key_base"
      AWS_ACCESS_KEY_ID: "your_access_key_id"
      AWS_SECRET_ACCESS_KEY: "your_secret_access_key"
      AWS_REGION: "your_region"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  database:
